// Template: Models (ApiModel.t4) version 4.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace API_MTIS.Empleado.Models
{
    public partial class Empleado
    {
        
        [Key]
        [Required]
        [MaxLength()]
        [MinLength(0)]
        public string NIF { get; set; }

        [Required]
        [MaxLength()]
        [MinLength(0)]
        public string Nombre { get; set; }

        [Required]
        [MaxLength()]
        [MinLength(0)]
        public string Apellidos { get; set; }

        [Required]
        [MaxLength()]
        [MinLength(0)]
        public string Poblacion { get; set; }

        [Required]
        [MaxLength()]
        [MinLength(0)]
        public string Direccion { get; set; }

        [Required]
        [MaxLength()]
        [MinLength(0)]
        public string Telefono { get; set; }

        [Required]
        [MaxLength()]
        [MinLength(0)]
        public string Email { get; set; }

        [Required]
        public DateTime FechaNacimiento { get; set; }

        [Required]
        [MaxLength()]
        [MinLength(0)]
        public string IBAN { get; set; }

        [Required]
        [MaxLength()]
        [MinLength(0)]
        public string NSS { get; set; }
    } // end class

} // end Models namespace

