// Template: Base Controller (ApiControllerBase.t4) version 4.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using API_MTIS.Empleado.Models;

// Do not modify this file. This code was generated by AMF Server Scaffolder

namespace API_MTIS.Empleado
{
    [RoutePrefix("empleado")]
    public partial class EmpleadoController : ApiController
    {


/// <summary>
		/// Crear un empleado - /empleado
		/// </summary>
		/// <param name="empleado"></param>
		/// <returns>Error</returns>
        [ResponseType(typeof(Error))]
        [HttpPost]
        [Route("empleado")]
        public virtual IHttpActionResult PostBase([FromBody] API_MTIS.Empleado.Models.Empleado empleado)
        {
            // Do not modify this code
                        return  ((IEmpleadoController)this).Post(empleado);
                    }

/// <summary>
		/// Obtener todos los datos del empleado - /empleado/{nif}
		/// </summary>
		/// <param name="Nif"></param>
		/// <returns>MultipleEmpleadoNifGet</returns>
        [ResponseType(typeof(MultipleEmpleadoNifGet))]
        [HttpGet]
        [Route("{nif}")]
        public virtual IHttpActionResult GetBase([FromUri] string Nif)
        {
            // Do not modify this code
                        return  ((IEmpleadoController)this).Get(Nif);
                    }

/// <summary>
		/// Modificar los datos del empleado - /empleado/{nif}
		/// </summary>
		/// <param name="empleado"></param>
		/// <param name="Nif"></param>
		/// <returns>Error</returns>
        [ResponseType(typeof(Error))]
        [HttpPut]
        [Route("{nif}")]
        public virtual IHttpActionResult PutBase([FromBody] API_MTIS.Empleado.Models.Empleado empleado,[FromUri] string Nif)
        {
            // Do not modify this code
                        return  ((IEmpleadoController)this).Put(empleado,Nif);
                    }

/// <summary>
		/// Borrar un empleado - /empleado/{nif}
		/// </summary>
		/// <param name="Nif"></param>
		/// <returns>Error</returns>
        [ResponseType(typeof(Error))]
        [HttpDelete]
        [Route("{nif}")]
        public virtual IHttpActionResult DeleteBase([FromUri] string Nif)
        {
            // Do not modify this code
                        return  ((IEmpleadoController)this).Delete(Nif);
                    }
    }
}
