// Template: Models (ApiModel.t4) version 4.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace API_MTIS.Utilidades.Models
{
    public partial class Error
    {
        

        [Required]
        [MaxLength()]
        [MinLength(0)]
        public int Codigo { get; set; }

        [Required]
        [MaxLength()]
        [MinLength(0)]
        public string Mensaje { get; set; }
    } // end class

} // end Models namespace

