// Template: Models (ApiModel.t4) version 4.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace API_MTIS.Seguridad.Models
{
    /// <summary>
    /// Multiple Response Types Ipstring, Error
    /// </summary>
    public partial class MultipleSeguridadNifGet
    {
        

        /// <summary>
        /// Niveles 
        /// </summary>

        public IList<string> Ipstring { get; set; }

        /// <summary>
        /// No existe el NIF 
        /// </summary>

        public Error Error { get; set; }
    } // end class

} // end Models namespace

